//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Technical_Software_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tickets()
        {
            this.Executors = new HashSet<Executors>();
            this.HistoryEntries = new HashSet<HistoryEntries>();
            this.TicketDocuments = new HashSet<TicketDocuments>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Requester { get; set; }
        public System.DateTime OpeningDate { get; set; }
        public int TicketStateId { get; set; }
        public int CategoryId { get; set; }
        public int ImportanceTypeId { get; set; }
        public int SolutionId { get; set; }
        public System.DateTime LastUpdate { get; set; }
    
        public virtual Categories Categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Executors> Executors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoryEntries> HistoryEntries { get; set; }
        public virtual ImportanceTypes ImportanceTypes { get; set; }
        public virtual Solutions Solutions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketDocuments> TicketDocuments { get; set; }
        public virtual TicketStates TicketStates { get; set; }
    }
}
