//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Technical_Software_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketDocuments
    {
        public int Id { get; set; }
        public int TicketId { get; set; }
        public int DocumentId { get; set; }
    
        public virtual Documents Documents { get; set; }
        public virtual Tickets Tickets { get; set; }
    }
}
